services:
  # php:
  #   image: php:8.2-apache
  #   container_name: php-container
  #   volumes:
  #     - ./:/var/www/html
  #   depends_on:
  #     - mysql
  #   networks:
  #     - app_network
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8086  # Remplace par un mot de passe sécurisé
      MYSQL_DATABASE: light_traffic_monitor          # Nom de la base de données par défaut
    ports:
      - "3308:3306"                       # Expose MySQL sur le port 3306
    volumes:
      - ./mysql_data:/var/lib/mysql         # Volume pour persister les données

  adminer:
    image: adminer:latest
    container_name: adminer-2
    restart: always
    ports:
      - "8082:8080"                       # Adminer accessible sur le port 8080

volumes:
  mysql_data: